name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool \
          pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev \
          libssl-dev automake
          
          export PATH=$PATH:~/.local/bin/
      # 4. 安装 Python 依赖
      - name: Install python dependencies
        run: |
          pip3 install --user --upgrade buildozer
          pip3 install aiohttp kivy['full'] loguru

      # 5. 构建 APK
      - name: Build APK
        run: buildozer -v android debug

      # 6. 上传 APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk